import { redirect } from "next/navigation";
import { db } from "@/lib/db";
import { currentSeller } from "@/lib/session";
import { naira } from "@/lib/money";
import { PrintButton } from "@/components/PrintButton";

export const dynamic = "force-dynamic";

// One page the student can attach to a loan application. Print to PDF from the browser.
export default async function Export() {
  const seller = await currentSeller();
  if (!seller) redirect("/login");
  // Test payments (demo mode) are never part of the income record.
  const rows = await db.ledgerEntry.findMany({ where: { sellerId: seller.id, NOT: { order: { credit: { rail: "simulated" } } } }, orderBy: { date: "asc" }, include: { order: { include: { credit: true } } } });

  const months = new Map<string, { sum: number; n: number }>();
  for (const r of rows) {
    const k = r.date.toLocaleDateString("en-NG", { month: "long", year: "numeric" });
    const c = months.get(k) ?? { sum: 0, n: 0 };
    months.set(k, { sum: c.sum + r.amountKobo, n: c.n + 1 });
  }
  const total = rows.reduce((a, r) => a + r.amountKobo, 0);
  const avg = rows.length ? Math.round(total / rows.length) : 0;
  const first = rows[0]?.date;
  const last = rows[rows.length - 1]?.date;

  return (
    <main className="space-y-6 bg-white p-2">
      <div className="no-print flex justify-between">
        <a href="/ledger" className="text-sm text-(--muted)">← Ledger</a>
        <PrintButton />
      </div>

      <header className="border-b border-(--line) pb-4">
        <h1 className="text-2xl font-bold">Verified income record</h1>
        <p className="text-sm text-(--muted)">Generated by Shigo on {new Date().toLocaleDateString("en-NG", { day: "numeric", month: "long", year: "numeric" })}</p>
      </header>

      <section className="grid grid-cols-2 gap-4 text-sm">
        <div><div className="text-(--muted)">Seller</div><div className="font-semibold">{seller.name}</div></div>
        <div><div className="text-(--muted)">Phone</div><div className="font-semibold">{seller.phone}</div></div>
        <div><div className="text-(--muted)">Receiving account</div><div className="font-semibold">{seller.bankName} {seller.accountNumber}</div></div>
        <div><div className="text-(--muted)">Period</div><div className="font-semibold">{first ? `${first.toLocaleDateString("en-NG")} to ${last?.toLocaleDateString("en-NG")}` : "no payments yet"}</div></div>
        <div><div className="text-(--muted)">Confirmed payments</div><div className="font-semibold">{rows.length}</div></div>
        <div><div className="text-(--muted)">Total received</div><div className="font-semibold">{naira(total)}</div></div>
        <div><div className="text-(--muted)">Average order</div><div className="font-semibold">{naira(avg)}</div></div>
        <div><div className="text-(--muted)">Months with inflows</div><div className="font-semibold">{months.size}</div></div>
      </section>

      <section>
        <h2 className="mb-2 font-semibold">By month</h2>
        <table className="w-full text-sm">
          <thead><tr className="border-b border-(--line) text-left text-(--muted)"><th className="py-1 pr-3">Month</th><th className="pr-3">Paid orders</th><th className="text-right">Received</th></tr></thead>
          <tbody>
            {[...months.entries()].map(([k, v]) => (
              <tr key={k} className="border-b border-(--line)"><td className="py-1 pr-3">{k}</td><td className="pr-3">{v.n}</td><td className="text-right">{naira(v.sum)}</td></tr>
            ))}
          </tbody>
        </table>
      </section>

      <section>
        <h2 className="mb-2 font-semibold">Every confirmed payment</h2>
        <table className="w-full text-xs">
          <thead><tr className="border-b border-(--line) text-left text-(--muted)"><th className="py-1 pr-3">Date</th><th className="pr-3">Order</th><th className="pr-3">Confirmed by</th><th className="text-right">Amount</th></tr></thead>
          <tbody>
            {rows.map((r) => (
              <tr key={r.id} className="border-b border-(--line)">
                <td className="py-1 pr-3">{r.date.toLocaleDateString("en-NG")}</td>
                <td className="pr-3">{r.order.reference}{r.order.note ? ` · ${r.order.note}` : ""}</td>
                <td className="pr-3">{r.order.credit?.rail ?? ""}{r.order.credit?.payerName ? ` · ${r.order.credit.payerName}` : ""}</td>
                <td className="text-right">{naira(r.amountKobo)}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </section>

      <p className="text-xs text-(--muted)">
        Each row is a credit the receiving bank notified Shigo of, matched to one order. This record is evidence the seller chooses to share.
        It is not a credit decision; a licensed lender makes that.
      </p>
    </main>
  );
}
